missing JS dependencies
core-js added to fix Error: Cannot find module 'core-js/modules/es6.array.sort' (see https://github.com/brunocodutra/webapp-webpack-plugin/issues/72)